# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fcg-webapi-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f1030566d14143da9847af37fbdcc9b1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_09ecebca48ab480cbe11f1c1746f6330 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f1030566d14143da9847af37fbdcc9b1 }}/panoch/teste-dockerhub:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fcg-webapi-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_60ba9ab99cfa473b8c71ffe70577359a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f1030566d14143da9847af37fbdcc9b1 }}/panoch/teste-dockerhub:${{ github.sha }}'